# ==========================================================
# CardioTox-UR — Home page
# ==========================================================

import streamlit as st
import pandas as pd
import numpy as np
import io, tempfile, os
from datetime import datetime

st.set_page_config(page_title="CardioTox-UR", layout="wide", page_icon="🫀")

from pipeline import predict_cardiotoxicity, AD_THRESHOLD
from report_utils import generate_single_pdf, generate_single_csv
from rdkit import Chem
from rdkit.Chem import Draw

st.markdown(
    "<div style='display:flex; align-items:center; gap:12px;'>"
    "<span><svg width='44' height='44' viewBox='0 0 24 24' fill='#E63946' xmlns='http://www.w3.org/2000/svg'><path d='M12 21s-6.7-4.35-9.33-8.2C.86 10.28 1.4 6.66 4.36 4.86 6.5 3.56 9.14 4.02 12 6.98 14.86 4.02 17.5 3.56 19.64 4.86 22.6 6.66 23.14 10.28 21.33 12.8 18.7 16.65 12 21 12 21z'/></svg></span>"
    "<h1 style='margin:0;'><span style='color:#E63946;'>Cardiotox</span>"
    "<span style='color:#2A9D8F;'>-UR</span></h1>"
    "</div>",
    unsafe_allow_html=True,
)
st.markdown("<p style='font-size:18px; color:#555;'>Multi-Channel Cardiotoxicity Predictor</p>", unsafe_allow_html=True)
st.caption("Predicts hERG / Cav / Nav ion-channel blockade risk and a fused cardiotoxicity risk score, from SMILES.")

st.warning(
    "⚠️ **Disclaimer:** CardioTox-UR is a computational research and educational tool. "
    "Predictions are generated by machine learning models trained on public bioactivity data "
    "and are **not a substitute for experimental assay data, clinical judgment, or regulatory "
    "decision-making**. Results should be interpreted as directional guidance for early-stage "
    "screening, especially for molecules flagged as outside the model's applicability domain."
)


if 'history' not in st.session_state:
    st.session_state.history = []

tab1, tab2, tab3 = st.tabs(["🔬 Single Prediction", "📋 Batch Prediction", "🕒 History"])

with tab1:
    with st.expander("Don't have a SMILES string?"):
        st.markdown(
            "Look up your compound on [PubChem](https://pubchem.ncbi.nlm.nih.gov/) — "
            "search by name, open the compound page, and copy the **Canonical SMILES** "
            "field under the 'Names and Identifiers' section."
        )

    st.markdown("**Try an example:**")
    example_compounds = {
        "Aspirin": "CC(=O)Oc1ccccc1C(=O)O",
        "Terfenadine": "CC(C)(C)c1ccc(cc1)C(O)CCCN1CCC(CC1)C(O)(c1ccccc1)c1ccccc1",
        "Verapamil": "COc1ccc(CCN(C)CCCC(C#N)(c2ccc(OC)c(OC)c2)C(C)C)cc1OC",
        "Amiodarone": "CCN(CC)CCOc1c(I)cc(cc1I)C(=O)c2c3ccccc3oc2CCCC",
    }
    ex_cols = st.columns(len(example_compounds))
    for col, (label, smi) in zip(ex_cols, example_compounds.items()):
        if col.button(label, key=f"example_{label}"):
            st.session_state["single_smiles"] = smi

    smiles_input = st.text_input("Enter SMILES", placeholder="e.g. CC(=O)Oc1ccccc1C(=O)O", key="single_smiles")

    if st.button("Predict", type="primary", key="single_predict_btn"):
        mol = Chem.MolFromSmiles(smiles_input) if smiles_input else None
        if mol is None:
            st.error("Invalid or empty SMILES string.")
        else:
            col1, col2 = st.columns([1, 2])
            with col1:
                img = Draw.MolToImage(mol, size=(300, 300))
                st.image(img, caption="Structure")

            with col2:
                with st.spinner("Running predictions..."):
                    result = predict_cardiotoxicity(smiles_input)

                tier_color = {'High': '🔴', 'Medium': '🟡', 'Low': '🟢'}
                st.metric("Composite Risk Score", f"{result['composite_score']:.3f}",
                           f"{tier_color.get(result['risk_tier'],'')} {result['risk_tier']} Risk")
                st.caption(f"Confidence: {result['confidence']}")

                st.write("**Per-channel blocker probability:**")
                c1, c2, c3 = st.columns(3)
                c1.metric("hERG (K+)", f"{result['herg_prob']:.3f}")
                c2.metric("Cav (Ca2+)", f"{result['ca_prob']:.3f}")
                c3.metric("Nav (Na+)", f"{result['na_prob']:.3f}")

                with st.expander("Applicability domain similarities"):
                    for ch, sim in result['ad_similarities'].items():
                        st.write(f"{ch.upper()}: max Tanimoto similarity to training set = {sim:.3f} "
                                 f"({'✓ in AD' if sim >= AD_THRESHOLD else '✗ outside AD'})")

                with tempfile.NamedTemporaryFile(suffix='.png', delete=False) as tmp_img:
                    img.save(tmp_img.name)
                    pdf_bytes = generate_single_pdf(smiles_input, result, mol_img_path=tmp_img.name)
                os.unlink(tmp_img.name)

                csv_str = generate_single_csv(smiles_input, result)

                dl1, dl2 = st.columns(2)
                dl1.download_button("📄 Download PDF report", pdf_bytes,
                                     "cardiotox_report.pdf", "application/pdf")
                dl2.download_button("📊 Download CSV", csv_str,
                                     "cardiotox_report.csv", "text/csv")

                st.session_state.history.append({
                    'Timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                    'Type': 'Single', 'SMILES': smiles_input,
                    'hERG_prob': round(result['herg_prob'], 3), 'Ca_prob': round(result['ca_prob'], 3),
                    'Na_prob': round(result['na_prob'], 3), 'Composite_score': round(result['composite_score'], 3),
                    'Risk_tier': result['risk_tier'], 'Confidence': result['confidence'],
                })

with tab2:
    st.markdown("Upload a CSV containing a column of SMILES strings.")
    uploaded_file = st.file_uploader("Upload CSV", type='csv', key="batch_upload")

    if uploaded_file is not None:
        df = pd.read_csv(uploaded_file)
        smiles_col = st.selectbox("Which column contains SMILES?", df.columns.tolist())

        if st.button("Run batch prediction", type="primary", key="batch_predict_btn"):
            progress = st.progress(0)
            batch_results = []

            for i, smi in enumerate(df[smiles_col]):
                try:
                    r = predict_cardiotoxicity(str(smi))
                    batch_results.append({
                        'SMILES': smi, 'hERG_prob': round(r['herg_prob'], 3),
                        'Ca_prob': round(r['ca_prob'], 3), 'Na_prob': round(r['na_prob'], 3),
                        'Composite_score': round(r['composite_score'], 3),
                        'Risk_tier': r['risk_tier'], 'Confidence': r['confidence'],
                    })
                except Exception as e:
                    batch_results.append({'SMILES': smi, 'hERG_prob': None, 'Ca_prob': None,
                                           'Na_prob': None, 'Composite_score': None,
                                           'Risk_tier': 'ERROR', 'Confidence': str(e)})
                progress.progress((i + 1) / len(df))

            results_df = pd.DataFrame(batch_results)
            st.dataframe(results_df, use_container_width=True)

            st.write("**Summary:**")
            st.write(results_df['Risk_tier'].value_counts())

            csv_buffer = io.StringIO()
            results_df.to_csv(csv_buffer, index=False)
            st.download_button("📊 Download results (CSV)", csv_buffer.getvalue(),
                                "cardiotox_batch_predictions.csv", "text/csv")

            st.session_state.history.append({
                'Timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'Type': f'Batch ({len(df)} compounds)', 'SMILES': f'{len(df)} compounds',
                'hERG_prob': None, 'Ca_prob': None, 'Na_prob': None,
                'Composite_score': None,
                'Risk_tier': f"{(results_df['Risk_tier']=='High').sum()} High / "
                              f"{(results_df['Risk_tier']=='Medium').sum()} Med / "
                              f"{(results_df['Risk_tier']=='Low').sum()} Low",
                'Confidence': '—',
            })

with tab3:
    if not st.session_state.history:
        st.info("No predictions yet this session. Run a single or batch prediction to see it logged here.")
    else:
        hist_df = pd.DataFrame(st.session_state.history)
        st.dataframe(hist_df, use_container_width=True)

        hist_csv = io.StringIO()
        hist_df.to_csv(hist_csv, index=False)
        col1, col2 = st.columns(2)
        col1.download_button("📊 Download full history (CSV)", hist_csv.getvalue(),
                              "cardiotox_history.csv", "text/csv")
        if col2.button("🗑 Clear history"):
            st.session_state.history = []
            st.rerun()

st.divider()
st.caption("Composite score = hERG_risk × (1 − mitigation_weight × mean(Ca_risk, Na_risk)). "
           "Ca/Na channel block is treated as electrophysiologically mitigating hERG-driven risk (CiPA-style fusion).")


st.markdown("<p style='text-align:center; font-size:20px; color:#444; margin-top:20px;'>This is an academic research project developed as a part of the requirement for the fulfillment of the Bachelor of Pharmacy (B.Pharm) degree.</p>", unsafe_allow_html=True)
